version: '3.8'
services:
  dowellflight:
    build:
      context: .
    container_name: dowellflight
    restart: always
    command: npm run dev

    ports:
      - 8007:8007
    expose:
      - "8007"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
networks:
  default:
    external: true
    name: webnet